// Features page copy in English and Hindi. Headlines are [before, accent, after], so the page keeps
// drawing the accent with its own highlighter. Workspace names like Generate, Refine, Stop, History and
// Private mode stay in Latin, since the workspace itself is in English.
import { MAX_COMPARE } from '../workspace/LeftPanel'

type Headline = [string, string, string]

const en = {
  chapters: [
    { title: 'Works without setup', line: 'No API keys to find. Sign in and generate.' },
    { title: 'One source, many drafts', line: 'A PDF or a link becomes briefs, posts, slides and more.' },
    { title: 'Your tokens, respected', line: 'New formats are added. Drafts you have are never paid for twice.' },
    { title: 'Talk to your draft', line: 'Ask for changes the way you’d ask a colleague.' },
    { title: 'Your key, your call', line: 'If your own key fails, we ask before switching.' },
    { title: 'Private mode', line: 'Drafts written on your own computer. Nothing leaves it.' },
  ],
  whyItMatters: 'Why it matters: ',
  preview: 'Preview',
  example: 'Example',
  /** The workspace's own short name for a format (ALL_FORMATS), or its translation. */
  formatName: (_label: string, short: string) => short,
  hero: {
    eyebrow: 'Features',
    title: ['One document. Every audience. ', 'No setup.', ''] as Headline,
    lead: 'Here is what Sankshep.ai does for you, one feature at a time, and why each one matters when a report lands on your desk and five people need something different from it.',
    tryIt: 'Try it on a document',
    navLabel: 'Features on this page',
  },
  noSetup: {
    title: ['No keys. ', 'No setup.', ' Just start.'] as Headline,
    lead: 'Most AI tools send you somewhere else first: make an account, find a secret key, paste it back in. Sankshep doesn’t.',
    body: 'We keep working keys for Groq, Gemini and Mistral on our side, and a good model is already picked for you. The first time you open the workspace, everything is ready: add your document, choose your formats, press Generate. If you have a key of your own you can add it, but you never have to.',
    why: 'your first draft is one click away, not a setup guide away. That is the difference between trying a tool and giving up on it.',
    visualTitle: 'Before your first draft',
    steps: [
      { label: 'Sign in', note: 'or use the demo account' },
      { label: 'Choose a model', note: 'already picked for you' },
      { label: 'Paste an API key', note: 'not needed' },
    ],
    model: 'Model',
    keyLabel: 'Groq API key',
    keyPlaceholder: 'Optional (gsk_…)',
    keyHint: 'Leave it empty to use Sankshep’s shared Groq keys.',
    generate: 'Generate draft',
    ready: 'Ready',
  },
  oneToMany: {
    title: ['One source. ', 'Ten ways', ' to share it.'] as Headline,
    body: 'Drop in a PDF, a Word file, a web link, a photo of a page, or just paste text. Pick the formats you want, and Sankshep writes every one of them at the same time, from that one source.',
    why: 'you read the report once. Your manager gets a summary, your network gets a post, Monday’s meeting gets slides, and nobody copies and pastes between five documents.',
    example: 'Example source, five formats, drafted in parallel',
    runAgain: 'Run it again',
    alsoOnList: (list: string) => `Also on the list: ${list}. Or describe a format of your own in plain words.`,
    listSeparator: ', ',
  },
  board: {
    draftLabel: (label: string) => `${label} draft`,
    ready: 'Ready',
    writing: 'Writing…',
    tiles: { summary: 'Executive Summary', slides: 'Slide Deck', linkedin: 'LinkedIn Post', thread: 'X / Twitter', translation: 'Translation · Hindi' },
    brief: {
      kicker: 'Executive brief',
      title: 'Rooftop solar for small shops',
      bullets: ['The government now pays 40% of installation costs.', 'Every state must offer net-metering.', 'Payback drops from 6.5 to 3.9 years.'],
      decision: 'Decision required',
      decisionBody: 'Approve a pilot across our ten largest stores this quarter.',
    },
    slide: {
      count: 'Slide 3 of 8',
      title: 'The subsidy, in one line',
      sub: '40% of the cost, paid up front',
      notesLabel: 'Speaker notes',
      notes: 'Start with the number people remember: forty percent. Then show what it means for one shop’s bill.',
    },
    post: 'Small shops just got a real reason to go solar. The new policy pays 40% of the setup, and every state now lets you sell spare power back.',
    thread: ['Rooftop solar just got 40% cheaper for small shops.', 'And net-metering is now in every state.', 'Payback: 3.9 years, down from 6.5.'],
  },
  noWaste: {
    title: ['Every token buys ', 'something new.', ''] as Headline,
    lead: 'Asked for two formats, then decided you want two more? Sankshep won’t quietly write the first two again.',
    body1: [
      'Before anything is sent, it checks which drafts are already on your canvas from the same source and settings. If some are, it asks: ',
      'generate only the new formats',
      ', or regenerate everything. Pick the first and only the drafts you don’t have yet are written. The ones you already have stay exactly as they are, edits included.',
    ] as Headline,
    body2: 'The same care runs through the rest of the app: small edits in Refine don’t send your whole document again, and Stop ends a run the moment you no longer need it.',
    why: 'tokens cost money on a paid key and run out on a free one. We treat them as yours, and spend them only on work you don’t already have.',
    visualTitle: 'You press Generate with four formats',
    choiceLabel: 'What to generate',
    onlyNew: 'Generate only new formats',
    all: 'Regenerate all',
    keptEdited: 'Kept, with your edits',
    kept: 'Kept as it is',
    againLost: 'Written again, edits lost',
    again: 'Written again',
    newSent: 'New, sent to the AI',
    sentCount: (sent: number, total: number) => `${sent} of ${total}`,
    sentSuffix: ' formats sent to the AI',
    onlyMissing: 'Only what you don’t have yet',
    everything: 'Everything, again',
  },
  refine: {
    title: ['Don’t rewrite it. ', 'Just ask.', ''] as Headline,
    body: 'Every draft has a small box underneath it. Type what you want changed, the way you’d say it to a colleague, and only that draft is rewritten. Everything else on the page stays put.',
    why: 'you stay in one place and keep what’s already good. And since Sankshep only reaches for the original when your request needs it, small edits don’t send your whole document again.',
    draftStart:
      'Small shops just got a real reason to go solar. Under the new 2026 rooftop policy, the government covers 40% of installation costs, and every state now has to offer net-metering, which means shops can sell the power they don’t use back to the grid. For a typical corner store, that turns a big upfront cost into a much smaller one.',
    steps: [
      {
        ask: 'Make it shorter',
        title: 'Too long? Say so.',
        body: 'Trim it, tighten it, cut it in half. Sankshep works from the draft itself for edits like this, so your facts stay exactly as they were.',
        draft: 'Small shops just got a real reason to go solar: the 2026 policy covers 40% of installation costs, and net-metering is now in every state.',
        added: '',
      },
      {
        ask: 'Sound more casual',
        title: 'Change the voice, keep the point.',
        body: 'Friendlier, more formal, more technical: the same facts come back in different words, without starting over.',
        draft: 'Running a small shop? Going solar just got a lot cheaper. The new policy pays 40% of the setup, and you can sell your spare power back to the grid.',
        added: '',
      },
      {
        ask: 'Add the budget figure from the report',
        title: 'Missing something? Ask for it.',
        body: 'When you ask for a fact that isn’t in the draft yet, Sankshep goes back to your original document to find it, rather than guessing.',
        draft: 'Running a small shop? Going solar just got a lot cheaper. The new policy pays 40% of the setup, backed by a ₹18,000 crore national budget, and you can sell your spare power back to the grid.',
        added: 'backed by a ₹18,000 crore national budget',
      },
    ],
    readsLabel: 'Reads: ',
    readsBoth: 'your draft and your original document',
    readsDraft: 'your draft only',
    postLabel: 'LinkedIn Post',
    reads: 'Reads',
    yourDraft: 'Your draft',
    wordCount: (before: number, after: number) => `${before} words before · ${after} after`,
    refineButton: 'Refine',
  },
  yourKey: {
    title: ['Your key, ', 'your call.', ''] as Headline,
    lead: 'If you add your own API key and it stops working, Sankshep doesn’t quietly swap in something else behind your back.',
    body1: 'Keys expire, hit their daily limit, or get pasted with a typo. When that happens, Sankshep pauses, shows you exactly what the provider said, and asks whether you’d like to use its free key instead. Say yes and your drafts carry on. Say no and nothing else is sent.',
    body2: 'The same goes for time. If a run is taking longer than you’d like, press Stop. Drafts that already finished stay on the page, and the rest are simply not written.',
    why: 'you always know whose key wrote your drafts, and you are never stuck waiting on a run you no longer need.',
    consent: {
      hint: 'Try the buttons: this is a preview, nothing is sent.',
      title: 'Your Groq API key didn’t work',
      question: "Would you like to generate this using Sankshep.ai's free API key instead?",
      cancel: 'Cancel',
      use: 'Use Sankshep Key',
      nothingSent: 'Nothing was sent.',
      back: 'You’re back where you started. Fix the key, or choose another model, whenever you’re ready.',
      ready: 'Draft ready',
      drafting: 'Drafting with Sankshep’s key…',
      doneBody: 'Written with Sankshep’s key, because you said so. Your own key is still in place for next time.',
      draftingBody: 'Only because you chose it. Your settings stay as they were.',
      again: 'Show the prompt again',
    },
    stop: {
      formats: ['Executive Summary', 'LinkedIn Post', 'X / Twitter', 'Slide Deck', 'Blog Post'],
      ready: 'Ready',
      notWritten: 'Not written',
      writing: 'Writing…',
      waiting: 'Waiting',
      stopped: (done: number, total: number) => `Stopped. ${done} of ${total} drafts finished and kept.`,
      allReady: (total: number) => `All ${total} drafts ready.`,
      pressStop: 'Press Stop at any moment.',
      idle: 'A five-draft run, sped up.',
      stopButton: 'Stop generating',
      generate: (total: number) => `Generate ${total} drafts`,
      runAgain: 'Run it again',
    },
  },
  privateMode: {
    title: ['Your documents ', 'never leave', ' your computer.'] as Headline,
    lead: 'Most AI writing tools only work by sending your document to someone else’s servers. Sankshep can do the whole job on your own machine.',
    body: 'Switch the workspace to Private and every draft is written by Qwen 2.5 VL, running locally through Ollama. Drafts stream onto the canvas as they’re written, Stop freezes them exactly where they are, and refining a draft stays on your machine too. Links are switched off in this mode, because a link can only be fetched by a cloud service.',
    why: 'legal, finance and government teams can finally use AI on the documents they need it for most: the ones that can’t be uploaded anywhere.',
    facts: [
      { title: 'Drafts on your own GPU', body: 'Qwen 2.5 VL runs through Ollama. The page talks to it at localhost:11434, straight from your browser, with no server in between and no API key.' },
      { title: 'Scans read in the browser', body: 'Images and scanned pages are read with on-device OCR, then passed to the model as text. That keeps each request small and fast.' },
      { title: 'History without the text', body: 'A private run records counts, formats and the model name. The source, the file name and every draft stay off the database.' },
      { title: 'Fits an 8 GB laptop GPU', body: 'Each request is held to a 4,096-token window, so a 7B model runs on an ordinary laptop, one draft at a time.' },
    ],
    path: {
      title: 'Where your document goes',
      modeLabel: 'Processing mode',
      cloud: 'Cloud APIs',
      local: 'Private',
      computer: 'Your computer',
      document: ['Your document', 'PDF, DOCX, scan'],
      browser: ['Sankshep', 'in your browser'],
      ollama: ['Ollama', 'qwen2.5vl:7b'],
      internet: 'The internet',
      nothingSent: 'Nothing sent',
      server: ['Sankshep server', 'shared keys'],
      provider: ['AI provider', 'Groq, Mistral, Gemini'],
      localNote: ['Local engine ready · qwen2.5vl:7b.', ' The document is read, drafted and refined inside the dashed line.'],
      cloudNote: ['Fastest, on any device.', ' The text crosses to Sankshep’s server and the AI provider to be drafted.'],
    },
  },
  everyday: {
    eyebrow: 'And the everyday things',
    title: 'The small things you’ll use every day.',
    items: [
      { title: 'Compare models side by side', body: `Run the same brief through up to ${MAX_COMPARE} models and read their drafts next to each other.` },
      { title: 'Write for the right readers', body: 'Pick managers, HR and sales, engineers or the general public, or describe your own readers and save them for next time.' },
      { title: 'Choose a tone once', body: 'Professional, technical, casual or academic, applied to every draft in the run.' },
      { title: 'Six Indian languages', body: 'Translate into Hindi, Gujarati, Marathi, Bengali, Telugu or Tamil, the whole document, line by line.' },
      { title: 'Read images and scans', body: 'Photos of pages and scanned PDFs are read first, so a picture of a report works as a source too.' },
      { title: 'Take it with you', body: 'Copy any draft, download it as Markdown or plain text, and take slide decks away as PowerPoint. Past runs wait for you in History.' },
    ],
  },
  closing: {
    title: ['Bring one document. ', 'Leave with the rest.', ''] as Headline,
    open: 'Open the workspace',
    how: 'See how it works',
  },
}

/** Hindi names for the workspace formats, keyed by their ALL_FORMATS label. */
const HI_FORMATS: Record<string, string> = {
  'Executive Summary': 'कार्यकारी सारांश',
  'LinkedIn Post': 'LinkedIn पोस्ट',
  'Twitter/X Post': 'X / Twitter',
  Video: 'वीडियो',
  'PPT Presentation': 'स्लाइड डेक',
  'Blog Post': 'ब्लॉग पोस्ट',
  Advisory: 'एडवाइज़री',
  Infographic: 'इन्फ़ोग्राफ़िक',
  'Simplified Explanation': 'सरल व्याख्या',
  'Language Translation': 'अनुवाद',
}

const hi: typeof en = {
  chapters: [
    { title: 'बिना सेटअप के काम करता है', line: 'कोई API कुंजी ढूँढनी नहीं। साइन इन करें और जनरेट करें।' },
    { title: 'एक स्रोत, कई ड्राफ़्ट', line: 'एक PDF या लिंक से ब्रीफ़, पोस्ट, स्लाइड और भी बहुत कुछ।' },
    { title: 'आपके टोकन की क़द्र', line: 'नए फ़ॉर्मेट जुड़ते हैं। जो ड्राफ़्ट आपके पास हैं, उन पर दोबारा ख़र्च नहीं।' },
    { title: 'अपने ड्राफ़्ट से बात करें', line: 'बदलाव वैसे ही माँगें जैसे किसी सहकर्मी से माँगते।' },
    { title: 'आपकी कुंजी, आपका फ़ैसला', line: 'आपकी कुंजी विफल हो, तो बदलने से पहले हम पूछते हैं।' },
    { title: 'Private mode', line: 'ड्राफ़्ट आपके अपने कंप्यूटर पर लिखे जाते हैं। कुछ भी बाहर नहीं जाता।' },
  ],
  whyItMatters: 'यह क्यों मायने रखता है: ',
  preview: 'प्रीव्यू',
  example: 'उदाहरण',
  formatName: (label: string, short: string) => HI_FORMATS[label] ?? short,
  hero: {
    eyebrow: 'फ़ीचर्स',
    title: ['एक दस्तावेज़। हर पाठक। ', 'कोई सेटअप नहीं।', ''],
    lead: 'Sankshep.ai आपके लिए क्या करता है, एक-एक फ़ीचर करके, और हर फ़ीचर तब क्यों मायने रखता है जब एक रिपोर्ट आपकी मेज़ पर आती है और पाँच लोगों को उससे अलग-अलग चीज़ चाहिए।',
    tryIt: 'किसी दस्तावेज़ पर आज़माएँ',
    navLabel: 'इस पेज के फ़ीचर्स',
  },
  noSetup: {
    title: ['न कुंजी। ', 'न सेटअप।', ' बस शुरू करें।'],
    lead: 'ज़्यादातर AI टूल पहले आपको कहीं और भेजते हैं: अकाउंट बनाओ, गुप्त कुंजी ढूँढो, उसे वापस पेस्ट करो। Sankshep ऐसा नहीं करता।',
    body: 'Groq, Gemini और Mistral की चालू कुंजियाँ हमारे पास रहती हैं, और एक अच्छा मॉडल पहले से आपके लिए चुना होता है। पहली बार वर्कस्पेस खोलते ही सब तैयार मिलता है: अपना दस्तावेज़ जोड़ें, फ़ॉर्मेट चुनें, Generate दबाएँ। आपके पास अपनी कुंजी हो तो जोड़ सकते हैं, पर इसकी कभी ज़रूरत नहीं।',
    why: 'आपका पहला ड्राफ़्ट बस एक क्लिक दूर है, किसी सेटअप गाइड जितना दूर नहीं। किसी टूल को आज़माने और उसे छोड़ देने में यही फ़र्क़ है।',
    visualTitle: 'आपके पहले ड्राफ़्ट से पहले',
    steps: [
      { label: 'साइन इन करें', note: 'या डेमो अकाउंट इस्तेमाल करें' },
      { label: 'मॉडल चुनें', note: 'पहले से चुना हुआ' },
      { label: 'API कुंजी पेस्ट करें', note: 'ज़रूरत नहीं' },
    ],
    model: 'मॉडल',
    keyLabel: 'Groq API कुंजी',
    keyPlaceholder: 'वैकल्पिक (gsk_…)',
    keyHint: 'Sankshep की साझा Groq कुंजियाँ इस्तेमाल करने के लिए इसे खाली छोड़ें।',
    generate: 'ड्राफ़्ट बनाएँ',
    ready: 'तैयार',
  },
  oneToMany: {
    title: ['एक स्रोत। शेयर करने के ', 'दस तरीक़े।', ''],
    body: 'PDF, Word फ़ाइल, वेब लिंक, किसी पेज की फ़ोटो डालें, या बस टेक्स्ट पेस्ट करें। जो फ़ॉर्मेट चाहिए वे चुनें, और Sankshep उसी एक स्रोत से सब एक साथ लिख देता है।',
    why: 'आप रिपोर्ट एक ही बार पढ़ते हैं। आपके मैनेजर को सारांश मिलता है, आपके नेटवर्क को पोस्ट, सोमवार की मीटिंग को स्लाइड, और किसी को पाँच दस्तावेज़ों के बीच कॉपी-पेस्ट नहीं करना पड़ता।',
    example: 'उदाहरण स्रोत, पाँच फ़ॉर्मेट, एक साथ लिखे गए',
    runAgain: 'फिर से चलाएँ',
    alsoOnList: (list: string) => `सूची में और भी: ${list}। या सीधे शब्दों में अपना ख़ुद का फ़ॉर्मेट बताएँ।`,
    listSeparator: ', ',
  },
  board: {
    draftLabel: (label: string) => `${label} ड्राफ़्ट`,
    ready: 'तैयार',
    writing: 'लिख रहा है…',
    tiles: { summary: 'कार्यकारी सारांश', slides: 'स्लाइड डेक', linkedin: 'LinkedIn पोस्ट', thread: 'X / Twitter', translation: 'अनुवाद · हिंदी' },
    brief: {
      kicker: 'कार्यकारी ब्रीफ़',
      title: 'छोटी दुकानों के लिए रूफ़टॉप सोलर',
      bullets: ['अब सरकार स्थापना लागत का 40% देती है।', 'हर राज्य को नेट-मीटरिंग देनी होगी।', 'लागत वसूली का समय 6.5 से घटकर 3.9 साल।'],
      decision: 'ज़रूरी निर्णय',
      decisionBody: 'इस तिमाही हमारे दस सबसे बड़े स्टोर में पायलट को मंज़ूरी दें।',
    },
    slide: {
      count: 'स्लाइड 3 / 8',
      title: 'सब्सिडी, एक लाइन में',
      sub: 'लागत का 40%, पहले ही चुकाया हुआ',
      notesLabel: 'वक्ता के नोट्स',
      notes: 'उस संख्या से शुरू करें जो लोगों को याद रहती है: चालीस प्रतिशत। फिर दिखाएँ कि एक दुकान के बिल पर इसका क्या असर होता है।',
    },
    post: 'छोटी दुकानों के पास अब सोलर अपनाने की असली वजह है। नई नीति सेटअप का 40% देती है, और अब हर राज्य में आप बची हुई बिजली वापस बेच सकते हैं।',
    thread: ['छोटी दुकानों के लिए रूफ़टॉप सोलर अब 40% सस्ता।', 'और नेट-मीटरिंग अब हर राज्य में।', 'लागत वसूली: 3.9 साल, पहले 6.5 थी।'],
  },
  noWaste: {
    title: ['हर टोकन से मिलता है ', 'कुछ नया।', ''],
    lead: 'दो फ़ॉर्मेट माँगे, फिर लगा कि दो और चाहिए? Sankshep पहले वाले दो को चुपचाप दोबारा नहीं लिखेगा।',
    body1: [
      'कुछ भी भेजने से पहले यह जाँचता है कि उसी स्रोत और सेटिंग से कौन-से ड्राफ़्ट पहले से आपके कैनवस पर हैं। अगर कुछ हैं, तो यह पूछता है: ',
      'सिर्फ़ नए फ़ॉर्मेट बनाएँ',
      ', या सब कुछ दोबारा बनाएँ। पहला चुनें, तो सिर्फ़ वही ड्राफ़्ट लिखे जाते हैं जो आपके पास अभी नहीं हैं। जो पहले से हैं, वे ठीक वैसे ही रहते हैं, आपके बदलावों के साथ।',
    ],
    body2: 'बाकी ऐप में भी यही ध्यान रखा गया है: Refine में छोटे बदलाव आपका पूरा दस्तावेज़ दोबारा नहीं भेजते, और जैसे ही आपको किसी रन की ज़रूरत न रहे, Stop उसे वहीं रोक देता है।',
    why: 'पेड कुंजी पर टोकन के पैसे लगते हैं और मुफ़्त कुंजी पर वे ख़त्म हो जाते हैं। हम उन्हें आपका मानते हैं, और सिर्फ़ उसी काम पर ख़र्च करते हैं जो आपके पास पहले से नहीं है।',
    visualTitle: 'आप चार फ़ॉर्मेट के साथ Generate दबाते हैं',
    choiceLabel: 'क्या बनाना है',
    onlyNew: 'सिर्फ़ नए फ़ॉर्मेट बनाएँ',
    all: 'सब दोबारा बनाएँ',
    keptEdited: 'आपके बदलावों के साथ रखा गया',
    kept: 'जैसा था वैसा रखा गया',
    againLost: 'दोबारा लिखा गया, बदलाव मिट गए',
    again: 'दोबारा लिखा गया',
    newSent: 'नया, AI को भेजा गया',
    sentCount: (sent: number, total: number) => `${total} में से ${sent}`,
    sentSuffix: ' फ़ॉर्मेट AI को भेजे गए',
    onlyMissing: 'सिर्फ़ वही जो अभी आपके पास नहीं',
    everything: 'सब कुछ, दोबारा',
  },
  refine: {
    title: ['ख़ुद दोबारा मत लिखिए। ', 'बस कहिए।', ''],
    body: 'हर ड्राफ़्ट के नीचे एक छोटा बॉक्स होता है। जो बदलना है वह वैसे ही लिखें जैसे किसी सहकर्मी से कहते, और सिर्फ़ वही ड्राफ़्ट दोबारा लिखा जाता है। पेज पर बाकी सब जस का तस रहता है।',
    why: 'आप एक ही जगह रहते हैं और जो पहले से अच्छा है उसे बनाए रखते हैं। और क्योंकि Sankshep मूल दस्तावेज़ तक तभी जाता है जब आपके अनुरोध को उसकी ज़रूरत हो, छोटे बदलाव आपका पूरा दस्तावेज़ दोबारा नहीं भेजते।',
    draftStart:
      'छोटी दुकानों के पास अब सोलर अपनाने की असली वजह है। 2026 की नई रूफ़टॉप नीति के तहत सरकार स्थापना लागत का 40% देती है, और अब हर राज्य को नेट-मीटरिंग देनी होगी, यानी दुकानें अपनी बची हुई बिजली ग्रिड को वापस बेच सकती हैं। किसी आम दुकान के लिए इसका मतलब है कि बड़ी शुरुआती लागत काफ़ी कम हो जाती है।',
    steps: [
      {
        ask: 'इसे छोटा करो',
        title: 'बहुत लंबा है? बस कह दीजिए।',
        body: 'छोटा करें, कसावट लाएँ, आधा कर दें। ऐसे बदलावों के लिए Sankshep ड्राफ़्ट से ही काम करता है, इसलिए आपके तथ्य ठीक वैसे ही रहते हैं।',
        draft: 'छोटी दुकानों के पास अब सोलर अपनाने की असली वजह है: 2026 की नीति स्थापना लागत का 40% देती है, और नेट-मीटरिंग अब हर राज्य में है।',
        added: '',
      },
      {
        ask: 'थोड़ा बोलचाल वाला बनाओ',
        title: 'अंदाज़ बदलें, बात वही रहे।',
        body: 'ज़्यादा दोस्ताना, ज़्यादा औपचारिक, ज़्यादा तकनीकी: वही तथ्य नए शब्दों में लौटते हैं, शुरू से लिखे बिना।',
        draft: 'छोटी दुकान चलाते हैं? सोलर अपनाना अब काफ़ी सस्ता हो गया है। नई नीति सेटअप का 40% देती है, और आप अपनी बची हुई बिजली ग्रिड को वापस बेच सकते हैं।',
        added: '',
      },
      {
        ask: 'रिपोर्ट से बजट का आँकड़ा जोड़ो',
        title: 'कुछ छूट गया? माँग लीजिए।',
        body: 'जब आप कोई ऐसा तथ्य माँगते हैं जो ड्राफ़्ट में अभी नहीं है, तो Sankshep अंदाज़ा लगाने के बजाय उसे ढूँढने के लिए आपके मूल दस्तावेज़ पर वापस जाता है।',
        draft: 'छोटी दुकान चलाते हैं? सोलर अपनाना अब काफ़ी सस्ता हो गया है। ₹18,000 करोड़ के राष्ट्रीय बजट के सहारे नई नीति सेटअप का 40% देती है, और आप अपनी बची हुई बिजली ग्रिड को वापस बेच सकते हैं।',
        added: '₹18,000 करोड़ के राष्ट्रीय बजट के सहारे',
      },
    ],
    readsLabel: 'पढ़ता है: ',
    readsBoth: 'आपका ड्राफ़्ट और आपका मूल दस्तावेज़',
    readsDraft: 'सिर्फ़ आपका ड्राफ़्ट',
    postLabel: 'LinkedIn पोस्ट',
    reads: 'पढ़ता है',
    yourDraft: 'आपका ड्राफ़्ट',
    wordCount: (before: number, after: number) => `पहले ${before} शब्द · बाद में ${after}`,
    refineButton: 'सुधारें',
  },
  yourKey: {
    title: ['आपकी कुंजी, ', 'आपका फ़ैसला।', ''],
    lead: 'अगर आप अपनी API कुंजी जोड़ते हैं और वह काम करना बंद कर दे, तो Sankshep आपको बताए बिना चुपचाप कुछ और नहीं लगा देता।',
    body1: 'कुंजियाँ एक्सपायर हो जाती हैं, अपनी रोज़ की सीमा तक पहुँच जाती हैं, या टाइपिंग की ग़लती के साथ पेस्ट हो जाती हैं। ऐसा होने पर Sankshep रुकता है, आपको ठीक-ठीक दिखाता है कि प्रोवाइडर ने क्या कहा, और पूछता है कि क्या आप उसकी जगह इसकी मुफ़्त कुंजी इस्तेमाल करना चाहेंगे। हाँ कहें, तो आपके ड्राफ़्ट जारी रहते हैं। ना कहें, तो आगे कुछ नहीं भेजा जाता।',
    body2: 'समय के साथ भी यही बात है। अगर कोई रन उम्मीद से ज़्यादा समय ले रहा है, तो Stop दबाएँ। जो ड्राफ़्ट पूरे हो चुके हैं वे पेज पर रहते हैं, और बाकी बस लिखे नहीं जाते।',
    why: 'आपको हमेशा पता रहता है कि आपके ड्राफ़्ट किसकी कुंजी से लिखे गए, और आपको कभी ऐसे रन का इंतज़ार नहीं करना पड़ता जिसकी अब ज़रूरत नहीं।',
    consent: {
      hint: 'बटन दबाकर देखें: यह एक प्रीव्यू है, कुछ नहीं भेजा जाता।',
      title: 'आपकी Groq API कुंजी काम नहीं कर रही',
      question: 'क्या आप इसकी जगह Sankshep.ai की मुफ़्त API कुंजी से इसे बनाना चाहेंगे?',
      cancel: 'रद्द करें',
      use: 'Sankshep कुंजी इस्तेमाल करें',
      nothingSent: 'कुछ नहीं भेजा गया।',
      back: 'आप वहीं लौट आए जहाँ से शुरू किया था। जब तैयार हों, कुंजी ठीक करें या कोई दूसरा मॉडल चुनें।',
      ready: 'ड्राफ़्ट तैयार',
      drafting: 'Sankshep की कुंजी से ड्राफ़्ट लिखा जा रहा है…',
      doneBody: 'Sankshep की कुंजी से लिखा गया, क्योंकि आपने कहा। आपकी अपनी कुंजी अगली बार के लिए अपनी जगह पर है।',
      draftingBody: 'सिर्फ़ इसलिए क्योंकि आपने चुना। आपकी सेटिंग वैसी ही रहती हैं।',
      again: 'संदेश फिर से दिखाएँ',
    },
    stop: {
      formats: ['कार्यकारी सारांश', 'LinkedIn पोस्ट', 'X / Twitter', 'स्लाइड डेक', 'ब्लॉग पोस्ट'],
      ready: 'तैयार',
      notWritten: 'नहीं लिखा गया',
      writing: 'लिख रहा है…',
      waiting: 'इंतज़ार में',
      stopped: (done: number, total: number) => `रोक दिया गया। ${total} में से ${done} ड्राफ़्ट पूरे हुए और रखे गए।`,
      allReady: (total: number) => `सभी ${total} ड्राफ़्ट तैयार।`,
      pressStop: 'किसी भी पल रोक सकते हैं।',
      idle: 'पाँच ड्राफ़्ट का रन, तेज़ गति में।',
      stopButton: 'बनाना रोकें',
      generate: (total: number) => `${total} ड्राफ़्ट बनाएँ`,
      runAgain: 'फिर से चलाएँ',
    },
  },
  privateMode: {
    title: ['आपके दस्तावेज़ आपके कंप्यूटर से ', 'कभी बाहर नहीं जाते।', ''],
    lead: 'ज़्यादातर AI लेखन टूल तभी काम करते हैं जब आपका दस्तावेज़ किसी और के सर्वर पर भेजा जाए। Sankshep पूरा काम आपकी अपनी मशीन पर कर सकता है।',
    body: 'वर्कस्पेस को Private पर करें, और हर ड्राफ़्ट Ollama के ज़रिए आपकी मशीन पर चलने वाला Qwen 2.5 VL लिखता है। ड्राफ़्ट लिखे जाते ही कैनवस पर दिखने लगते हैं, Stop उन्हें ठीक वहीं रोक देता है, और ड्राफ़्ट सुधारना भी आपकी मशीन पर ही होता है। इस मोड में लिंक बंद रहते हैं, क्योंकि लिंक सिर्फ़ कोई क्लाउड सेवा ही ला सकती है।',
    why: 'क़ानूनी, वित्त और सरकारी टीमें आख़िरकार उन दस्तावेज़ों पर AI इस्तेमाल कर सकती हैं जिनके लिए उन्हें इसकी सबसे ज़्यादा ज़रूरत है: वे दस्तावेज़ जो कहीं अपलोड नहीं किए जा सकते।',
    facts: [
      { title: 'आपके अपने GPU पर ड्राफ़्ट', body: 'Qwen 2.5 VL, Ollama के ज़रिए चलता है। पेज सीधे आपके ब्राउज़र से localhost:11434 पर उससे बात करता है, बीच में न कोई सर्वर, न कोई API कुंजी।' },
      { title: 'स्कैन ब्राउज़र में पढ़े जाते हैं', body: 'इमेज और स्कैन किए पेज डिवाइस पर OCR से पढ़े जाते हैं, फिर टेक्स्ट के रूप में मॉडल को दिए जाते हैं। इससे हर अनुरोध छोटा और तेज़ रहता है।' },
      { title: 'टेक्स्ट के बिना History', body: 'Private रन सिर्फ़ गिनती, फ़ॉर्मेट और मॉडल का नाम दर्ज करता है। स्रोत, फ़ाइल का नाम और हर ड्राफ़्ट डेटाबेस से दूर रहते हैं।' },
      { title: '8 GB लैपटॉप GPU में चल जाता है', body: 'हर अनुरोध 4,096 टोकन की सीमा में रहता है, इसलिए 7B मॉडल एक आम लैपटॉप पर चल जाता है, एक बार में एक ड्राफ़्ट।' },
    ],
    path: {
      title: 'आपका दस्तावेज़ कहाँ जाता है',
      modeLabel: 'प्रोसेसिंग मोड',
      cloud: 'क्लाउड API',
      local: 'Private',
      computer: 'आपका कंप्यूटर',
      document: ['आपका दस्तावेज़', 'PDF, DOCX, स्कैन'],
      browser: ['Sankshep', 'आपके ब्राउज़र में'],
      ollama: ['Ollama', 'qwen2.5vl:7b'],
      internet: 'इंटरनेट',
      nothingSent: 'कुछ नहीं भेजा गया',
      server: ['Sankshep सर्वर', 'साझा कुंजियाँ'],
      provider: ['AI प्रोवाइडर', 'Groq, Mistral, Gemini'],
      localNote: ['लोकल इंजन तैयार · qwen2.5vl:7b।', ' दस्तावेज़ बिंदीदार रेखा के अंदर ही पढ़ा, लिखा और सुधारा जाता है।'],
      cloudNote: ['सबसे तेज़, किसी भी डिवाइस पर।', ' ड्राफ़्ट लिखने के लिए टेक्स्ट Sankshep के सर्वर और AI प्रोवाइडर तक जाता है।'],
    },
  },
  everyday: {
    eyebrow: 'और रोज़ के काम की चीज़ें',
    title: 'छोटी चीज़ें, जिन्हें आप हर दिन इस्तेमाल करेंगे।',
    items: [
      { title: 'मॉडलों की साथ-साथ तुलना', body: `एक ही ब्रीफ़ को ${MAX_COMPARE} तक मॉडलों से चलाएँ और उनके ड्राफ़्ट एक-दूसरे के बगल में पढ़ें।` },
      { title: 'सही पाठकों के लिए लिखें', body: 'मैनेजर, HR और सेल्स, इंजीनियर या आम जनता चुनें, या अपने पाठकों का वर्णन करके उन्हें अगली बार के लिए सहेज लें।' },
      { title: 'टोन एक बार चुनें', body: 'पेशेवर, तकनीकी, बोलचाल वाली या अकादमिक, रन के हर ड्राफ़्ट पर लागू।' },
      { title: 'छह भारतीय भाषाएँ', body: 'पूरे दस्तावेज़ का, लाइन-दर-लाइन, हिंदी, गुजराती, मराठी, बांग्ला, तेलुगु या तमिल में अनुवाद करें।' },
      { title: 'इमेज और स्कैन पढ़ें', body: 'पेजों की फ़ोटो और स्कैन किए PDF पहले पढ़े जाते हैं, इसलिए किसी रिपोर्ट की तस्वीर भी स्रोत बन सकती है।' },
      { title: 'साथ ले जाएँ', body: 'कोई भी ड्राफ़्ट कॉपी करें, उसे Markdown या सादे टेक्स्ट के रूप में डाउनलोड करें, और स्लाइड डेक PowerPoint के रूप में ले जाएँ। पिछले रन History में आपका इंतज़ार करते हैं।' },
    ],
  },
  closing: {
    title: ['एक दस्तावेज़ लाइए। ', 'बाकी सब लेकर जाइए।', ''],
    open: 'वर्कस्पेस खोलें',
    how: 'देखें यह कैसे काम करता है',
  },
}

export const FEATURES_COPY = { en, hi }
