// Landing page copy in English and Hindi. Feature names that appear in the (English) workspace,
// like "Private mode" and "Cloud mode", and tool names in the pipeline tags stay in Latin.

const en = {
  hero: {
    sihLine: 'Smart India Hackathon 2026 · SIH26154 · NTRO',
    sihProblem: 'Gen AI Platform for Automated Content Transformation',
    chip: 'AI Content Transformation',
    title: 'Turn long, messy reports into ready-to-share content.',
    body: 'Drop in research papers, policy briefs, YouTube links, or rough notes. Sankshep instantly creates clean summaries, video scripts, LinkedIn posts, and slide decks — keeping your data safe and private.',
    launch: 'Launch Workspace',
    seeHow: 'See How It Works',
    noCard: 'No credit card',
    privateMode: 'Fully on-device Private mode',
  },
  explainer: {
    label: 'How Sankshep works',
    scenes: [
      { tag: 'Step 1 — Ingest', caption: 'Drop in any report, paper, or link.' },
      { tag: 'Step 2 — Understand', caption: 'Sankshep reads & verifies every page.' },
      { tag: 'Step 3 — Choose', caption: 'Pick every format you need.' },
      { tag: 'Step 4 — Deliver', caption: 'Get polished, source-linked outputs.' },
    ],
    scene: 'Scene',
    pause: 'Pause',
    play: 'Play',
    fileMeta: '42 MB · 84 pages',
    sources: ['PDF', 'DOCX', 'MP4', 'YouTube', 'Web URL'],
    analysing: 'Analysing context · verifying sources',
    chips: ['Executive Summary', '5-Slide Deck', 'Video Script', 'LinkedIn Post'],
    outputs: [
      { t: 'Executive Summary', d: '1-page brief · exported' },
      { t: '5-Slide Deck', d: 'PPTX · ready to present' },
      { t: 'Video Script', d: '2-min narration + scenes' },
    ],
  },
  demo: {
    eyebrow: 'Demo video',
    title: 'Watch Sankshep *at work.*',
    body: 'Our Smart India Hackathon 2026 walkthrough of the workspace.',
    open: 'Open on YouTube',
    frameTitle: 'Sankshep.ai demo video',
  },
  security: {
    eyebrow: 'Privacy first',
    title: 'Your documents never have to *leave your computer.*',
    body: 'Contracts, financials, board papers: some documents can’t go to a cloud AI at all. Sankshep’s Private mode is built for them. One switch in the workspace moves every step onto your own machine, from reading the file to writing the last draft.',
    link: 'See how Private mode works',
    caption: 'What leaves your computer in Cloud mode and in Private mode',
    head: ['What leaves your computer', 'Cloud mode', 'Private mode'],
    rows: [
      { what: 'Your document’s text', cloud: 'Sent to the AI provider', local: 'Stays on your computer' },
      { what: 'Drafts and refinements', cloud: 'Written by the provider', local: 'Written by your own GPU' },
      { what: 'Images and scanned pages', cloud: 'Read by a vision model', local: 'Read by OCR in the browser' },
      { what: 'Saved to History', cloud: 'Excerpt and drafts', local: 'Counts only, never text' },
    ],
    items: [
      { title: 'Runs on your own machine', body: 'Private mode writes every draft with Qwen 2.5 VL through Ollama on your computer. Nothing is sent to Sankshep or to any AI provider.' },
      { title: 'Nothing to train on', body: 'No provider receives your text, so no one can keep it, log it or train a model on it.' },
      { title: 'Fits an everyday laptop', body: 'Each request is held to a 4,096-token window, so a 7B model runs in 8 GB of GPU memory and drafts stream in as they’re written.' },
    ],
  },
  pipeline: {
    eyebrow: 'The pipeline',
    title: 'How Sankshep turns one source into every format.',
    body: 'One canonical understanding of your content feeds a private, agentic engine — so every deliverable stays consistent, verifiable, and on-brand.',
    step: 'Step',
    stages: [
      { title: 'Ingest', desc: 'Drop in PDFs, docs, audio, video, or just paste a link — from anywhere you keep your content.', tags: ['PDF', 'Audio', 'Video', 'URL'], live: 'Q3_Report.pdf uploaded — 42 MB accepted.' },
      { title: 'Parse', desc: 'We read the layout, tables, and even spoken words, then turn everything into clean, usable text.', tags: ['LlamaParse', 'Unstructured', 'Whisper'], live: 'Layout, tables & speech extracted to clean text.' },
      { title: 'Chunk', desc: 'The text is broken into bite-sized pieces that each keep their full meaning and context.', tags: ['Semantic'], live: 'Split into coherent, context-aware passages.' },
      { title: 'Embed & store', desc: 'Everything is saved in one searchable place, so the right passage is always easy to find.', tags: ['pgvector'], live: 'Embeddings written to a unified pgvector store.' },
      { title: 'Orchestrate', desc: 'Smart assistants take over and decide exactly what to build and in what order.', tags: ['LangGraph', 'Router'], live: 'Router dispatches the Generator & Critic agents.' },
      { title: 'Generate', desc: 'Your summary, slide deck, video script, and social posts are all drafted at the same time.', tags: ['vLLM', 'Llama-3'], live: 'Summary, deck, script & posts drafted in parallel.' },
      { title: 'Validate', desc: 'Every draft is fact-checked against your source and rewritten until it holds up.', tags: ['Pydantic', 'Reflection'], live: 'Schema-checked; rejected drafts revised in a loop.' },
      { title: 'Deliver', desc: 'You get polished, ready-to-share files — with every claim linked back to the source.', tags: ['Deck', 'PDF', 'Word', 'Social'], live: 'Source-linked deliverables exported to you.' },
    ],
    highlights: [
      { k: 'No waiting around', v: 'Upload big files and keep working — Sankshep processes them in the background and never times out.' },
      { k: 'Everything in one place', v: 'Your content and its meaning live together in one spot, so answers stay consistent and never drift.' },
      { k: 'Checks its own work', v: 'Sankshep drafts, then reviews and fixes itself — so every output stays true to your original source.' },
    ],
  },
  chat: {
    eyebrow: 'Sankshep Chat',
    title: 'Edit anything by just asking.',
    body: 'Need to change the tone or shorten a 10-page brief? Just type your request below the output, and Sankshep rewrites it in seconds.',
    generating: 'generating',
    // Plain text, highlighted, plain, highlighted, plain.
    prompt: ['Turn this ', '20-page security advisory', ' into a ', '3-bullet quick brief', '.'],
    placeholder: 'Ask Sankshep to refine…',
    regenerate: 'Regenerate',
  },
  how: {
    eyebrow: 'How it works',
    title: 'From raw source to polished deliverable in three steps.',
    explore: 'Explore all formats',
    steps: [
      { title: 'Drop in any content up to 30 MB', body: 'Drag & drop PDFs, docs, and images, or paste web URLs. Sankshep reads them all.' },
      { title: 'Pick every format you need', body: 'Choose from Summaries, Advisories, Slides, Video Scripts, or Social posts — all at once.' },
      { title: 'Design custom formats with AI', body: 'Describe how you want the output arranged, and AI builds a custom template instantly.' },
    ],
    drop: 'Drop files or paste a URL',
    fileTypes: 'PDF · DOCX · MP4 · Web',
    tags: ['Summary', 'Advisory', 'Slides', 'Video', 'LinkedIn', 'Twitter/X'],
    promptLabel: 'Prompt ›',
    promptText: '"A one-column brief with a risk table and 3 action items."',
    building: 'Building custom template…',
  },
  cta: {
    title: 'Give your reports a second life.',
    body: 'Private, multi-format content creation — from the same trusted source.',
    button: 'Open Workspace',
  },
}

const hi: typeof en = {
  hero: {
    sihLine: 'स्मार्ट इंडिया हैकाथॉन 2026 · SIH26154 · NTRO',
    sihProblem: 'स्वचालित कंटेंट रूपांतरण के लिए Gen AI प्लेटफ़ॉर्म',
    chip: 'AI कंटेंट रूपांतरण',
    title: 'लंबी, उलझी रिपोर्टों को शेयर करने लायक कंटेंट में बदलें।',
    body: 'रिसर्च पेपर, नीति दस्तावेज़, YouTube लिंक या कच्चे नोट्स डालें। Sankshep तुरंत साफ़-सुथरे सारांश, वीडियो स्क्रिप्ट, LinkedIn पोस्ट और स्लाइड डेक बना देता है, और आपका डेटा सुरक्षित और निजी रखता है।',
    launch: 'वर्कस्पेस खोलें',
    seeHow: 'देखें यह कैसे काम करता है',
    noCard: 'क्रेडिट कार्ड की ज़रूरत नहीं',
    privateMode: 'Private mode, पूरी तरह आपके डिवाइस पर',
  },
  explainer: {
    label: 'Sankshep कैसे काम करता है',
    scenes: [
      { tag: 'चरण 1: अपलोड', caption: 'कोई भी रिपोर्ट, पेपर या लिंक डालें।' },
      { tag: 'चरण 2: समझ', caption: 'Sankshep हर पेज पढ़ता और जाँचता है।' },
      { tag: 'चरण 3: चुनाव', caption: 'जो भी फ़ॉर्मेट चाहिए, सब चुनें।' },
      { tag: 'चरण 4: डिलीवरी', caption: 'स्रोत से जुड़े, तैयार आउटपुट पाएँ।' },
    ],
    scene: 'दृश्य',
    pause: 'रोकें',
    play: 'चलाएँ',
    fileMeta: '42 MB · 84 पेज',
    sources: ['PDF', 'DOCX', 'MP4', 'YouTube', 'वेब URL'],
    analysing: 'संदर्भ समझ रहा है · स्रोत जाँच रहा है',
    chips: ['कार्यकारी सारांश', '5 स्लाइड का डेक', 'वीडियो स्क्रिप्ट', 'LinkedIn पोस्ट'],
    outputs: [
      { t: 'कार्यकारी सारांश', d: '1 पेज का ब्रीफ़ · एक्सपोर्ट हो गया' },
      { t: '5 स्लाइड का डेक', d: 'PPTX · प्रस्तुति के लिए तैयार' },
      { t: 'वीडियो स्क्रिप्ट', d: '2 मिनट का नैरेशन और दृश्य' },
    ],
  },
  demo: {
    eyebrow: 'डेमो वीडियो',
    title: 'Sankshep को *काम करते देखें।*',
    body: 'स्मार्ट इंडिया हैकाथॉन 2026 के लिए वर्कस्पेस का हमारा वॉकथ्रू (अंग्रेज़ी में)।',
    open: 'YouTube पर खोलें',
    frameTitle: 'Sankshep.ai डेमो वीडियो',
  },
  security: {
    eyebrow: 'गोपनीयता सबसे पहले',
    title: 'आपके दस्तावेज़ों को कभी *आपके कंप्यूटर से बाहर नहीं जाना पड़ता।*',
    body: 'अनुबंध, वित्तीय रिकॉर्ड, बोर्ड के कागज़ात: कुछ दस्तावेज़ क्लाउड AI को भेजे ही नहीं जा सकते। Sankshep का Private mode इन्हीं के लिए बना है। वर्कस्पेस में एक स्विच दबाते ही हर काम आपकी अपनी मशीन पर होने लगता है, फ़ाइल पढ़ने से लेकर आख़िरी ड्राफ़्ट लिखने तक।',
    link: 'देखें Private mode कैसे काम करता है',
    caption: 'Cloud mode और Private mode में आपके कंप्यूटर से क्या बाहर जाता है',
    head: ['आपके कंप्यूटर से क्या बाहर जाता है', 'Cloud mode', 'Private mode'],
    rows: [
      { what: 'आपके दस्तावेज़ का टेक्स्ट', cloud: 'AI प्रोवाइडर को भेजा जाता है', local: 'आपके कंप्यूटर पर ही रहता है' },
      { what: 'ड्राफ़्ट और सुधार', cloud: 'प्रोवाइडर लिखता है', local: 'आपका अपना GPU लिखता है' },
      { what: 'इमेज और स्कैन किए पेज', cloud: 'विज़न मॉडल पढ़ता है', local: 'ब्राउज़र में OCR से पढ़े जाते हैं' },
      { what: 'History में सहेजा जाता है', cloud: 'अंश और ड्राफ़्ट', local: 'सिर्फ़ गिनती, टेक्स्ट कभी नहीं' },
    ],
    items: [
      { title: 'आपकी अपनी मशीन पर चलता है', body: 'Private mode हर ड्राफ़्ट आपके कंप्यूटर पर Ollama के ज़रिए Qwen 2.5 VL से लिखता है। Sankshep या किसी AI प्रोवाइडर को कुछ नहीं भेजा जाता।' },
      { title: 'ट्रेनिंग के लिए कुछ नहीं', body: 'किसी प्रोवाइडर को आपका टेक्स्ट मिलता ही नहीं, इसलिए न कोई उसे रख सकता है, न लॉग कर सकता है, न उस पर मॉडल ट्रेन कर सकता है।' },
      { title: 'आम लैपटॉप पर भी चलता है', body: 'हर अनुरोध 4,096 टोकन की सीमा में रहता है, इसलिए 7B मॉडल 8 GB GPU मेमोरी में चल जाता है और ड्राफ़्ट लिखे जाते ही दिखने लगते हैं।' },
    ],
  },
  pipeline: {
    eyebrow: 'पाइपलाइन',
    title: 'Sankshep एक स्रोत को हर फ़ॉर्मेट में कैसे बदलता है।',
    body: 'आपके कंटेंट की एक ही प्रामाणिक समझ एक निजी, एजेंट-आधारित इंजन को चलाती है, ताकि हर डिलीवरेबल एक-सा, जाँचने योग्य और आपके ब्रांड के अनुरूप रहे।',
    step: 'चरण',
    stages: [
      { title: 'इनपुट', desc: 'PDF, डॉक्यूमेंट, ऑडियो, वीडियो डालें या बस एक लिंक पेस्ट करें, आपका कंटेंट जहाँ भी हो।', tags: ['PDF', 'ऑडियो', 'वीडियो', 'URL'], live: 'Q3_Report.pdf अपलोड हुई, 42 MB स्वीकार।' },
      { title: 'पार्सिंग', desc: 'हम लेआउट, टेबल और बोले गए शब्द तक पढ़ते हैं, फिर सब कुछ साफ़, काम के टेक्स्ट में बदल देते हैं।', tags: ['LlamaParse', 'Unstructured', 'Whisper'], live: 'लेआउट, टेबल और आवाज़ से साफ़ टेक्स्ट निकाला गया।' },
      { title: 'टुकड़े', desc: 'टेक्स्ट को छोटे-छोटे हिस्सों में बाँटा जाता है, और हर हिस्सा अपना पूरा अर्थ और संदर्भ बनाए रखता है।', tags: ['Semantic'], live: 'सुसंगत, संदर्भ समझने वाले अंशों में बाँटा गया।' },
      { title: 'एम्बेड और स्टोर', desc: 'सब कुछ एक खोजने योग्य जगह पर सहेजा जाता है, ताकि सही अंश हमेशा आसानी से मिल जाए।', tags: ['pgvector'], live: 'एम्बेडिंग एक साझा pgvector स्टोर में लिखी गईं।' },
      { title: 'संचालन', desc: 'स्मार्ट असिस्टेंट काम संभालते हैं और तय करते हैं कि क्या बनाना है और किस क्रम में।', tags: ['LangGraph', 'Router'], live: 'Router ने Generator और Critic एजेंट को काम सौंपा।' },
      { title: 'जनरेट', desc: 'आपका सारांश, स्लाइड डेक, वीडियो स्क्रिप्ट और सोशल पोस्ट, सब एक साथ लिखे जाते हैं।', tags: ['vLLM', 'Llama-3'], live: 'सारांश, डेक, स्क्रिप्ट और पोस्ट एक साथ तैयार।' },
      { title: 'जाँच', desc: 'हर ड्राफ़्ट को आपके स्रोत से मिलाकर जाँचा जाता है और तब तक दोबारा लिखा जाता है जब तक वह खरा न उतरे।', tags: ['Pydantic', 'Reflection'], live: 'स्कीमा से जाँचा गया; अस्वीकृत ड्राफ़्ट बार-बार सुधारे गए।' },
      { title: 'डिलीवरी', desc: 'आपको शेयर करने के लिए तैयार फ़ाइलें मिलती हैं, और हर दावा स्रोत से जुड़ा होता है।', tags: ['डेक', 'PDF', 'Word', 'सोशल'], live: 'स्रोत से जुड़े डिलीवरेबल आपको एक्सपोर्ट किए गए।' },
    ],
    highlights: [
      { k: 'इंतज़ार नहीं', v: 'बड़ी फ़ाइलें अपलोड करें और काम करते रहें। Sankshep उन्हें बैकग्राउंड में प्रोसेस करता है और कभी टाइम-आउट नहीं होता।' },
      { k: 'सब कुछ एक जगह', v: 'आपका कंटेंट और उसका अर्थ एक ही जगह रहते हैं, इसलिए जवाब एक-से रहते हैं और भटकते नहीं।' },
      { k: 'अपना काम ख़ुद जाँचता है', v: 'Sankshep ड्राफ़्ट लिखता है, फिर ख़ुद उसकी समीक्षा करके सुधारता है, ताकि हर आउटपुट आपके मूल स्रोत के प्रति सच्चा रहे।' },
    ],
  },
  chat: {
    eyebrow: 'Sankshep Chat',
    title: 'बस कहिए, और कुछ भी बदलवाइए।',
    body: 'टोन बदलनी है या 10 पेज का ब्रीफ़ छोटा करना है? आउटपुट के नीचे बस अपना अनुरोध लिखें, और Sankshep कुछ ही सेकंड में उसे दोबारा लिख देता है।',
    generating: 'लिख रहा है',
    prompt: ['इस ', '20 पेज की सुरक्षा एडवाइज़री', ' को ', '3 बिंदुओं वाले छोटे ब्रीफ़', ' में बदलो।'],
    placeholder: 'Sankshep से सुधार करवाएँ…',
    regenerate: 'दोबारा बनाएँ',
  },
  how: {
    eyebrow: 'यह कैसे काम करता है',
    title: 'कच्चे स्रोत से तैयार डिलीवरेबल तक, तीन चरणों में।',
    explore: 'सभी फ़ॉर्मेट देखें',
    steps: [
      { title: '30 MB तक का कोई भी कंटेंट डालें', body: 'PDF, डॉक्यूमेंट और इमेज खींचकर छोड़ें, या वेब URL पेस्ट करें। Sankshep सब पढ़ लेता है।' },
      { title: 'जो फ़ॉर्मेट चाहिए, सब चुनें', body: 'सारांश, एडवाइज़री, स्लाइड, वीडियो स्क्रिप्ट या सोशल पोस्ट में से चुनें, सब एक साथ।' },
      { title: 'AI से अपने फ़ॉर्मेट बनाएँ', body: 'बताइए कि आउटपुट कैसे सजा हो, और AI तुरंत आपके लिए टेम्पलेट बना देता है।' },
    ],
    drop: 'फ़ाइलें डालें या URL पेस्ट करें',
    fileTypes: 'PDF · DOCX · MP4 · वेब',
    tags: ['सारांश', 'एडवाइज़री', 'स्लाइड', 'वीडियो', 'LinkedIn', 'Twitter/X'],
    promptLabel: 'प्रॉम्प्ट ›',
    promptText: '"जोखिम तालिका और 3 कार्य-बिंदुओं वाला, एक कॉलम का ब्रीफ़।"',
    building: 'कस्टम टेम्पलेट बन रहा है…',
  },
  cta: {
    title: 'अपनी रिपोर्टों को नया जीवन दें।',
    body: 'निजी, कई फ़ॉर्मेट में कंटेंट, एक ही भरोसेमंद स्रोत से।',
    button: 'वर्कस्पेस खोलें',
  },
}

export const LANDING_COPY = { en, hi }
